Repository spring-projects/spring-pulsar, pull requests merged in 2024-03, with the labels that each got.

#595 Upgrade enterprise gradle plugin
  settings.gradle
Labels: theme: build

#600 Publish the spring-pulsar-test module
  README.adoc
  spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/testing-applications.adoc
  spring-pulsar-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
  spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/aot/package-info.java
  spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/support/package-info.java
  spring-pulsar-test/spring-pulsar-test.gradle
  spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/PulsarTestContainerSupport.java
  spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/model/package-info.java
  spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/package-info.java
  spring-pulsar/src/main/java/org/springframework/pulsar/aot/package-info.java
Labels: theme: build, type: documentation, theme: testing

#603 Update to Reactor 2023.0.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#602 Deprecate ProducerBuilderConfigurationUtil
  spring-pulsar/src/main/java/org/springframework/pulsar/core/ProducerBuilderConfigurationUtil.java
Labels: type: deprecation

#604 Update Spring Framework 6.1.5
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#605 Update to Micrometer 1.13.0-M2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#607 Update to Jackson 2.17.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#608 Update to Pulsar 3.2.1
  gradle/libs.versions.toml
  spring-pulsar-sample-apps/sample-failover-custom-router/compose.yaml
  spring-pulsar-sample-apps/sample-imperative-produce-consume/compose.yaml
  spring-pulsar-sample-apps/sample-pulsar-binder/compose.yaml
  spring-pulsar-sample-apps/sample-pulsar-functions/download-connectors.sh
  spring-pulsar-sample-apps/sample-pulsar-reader/compose.yaml
  spring-pulsar-sample-apps/sample-reactive/compose.yaml
  tools/pulsar/docker/standalone/pulsar-start.sh
Labels: type: dependency-upgrade

#610 Update Micrometer to 1.12.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#611 Update Micrometer Tracing to 1.2.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#612 Update Spring Framework to 6.1.5
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#613 Update Jackson to 2.15.4
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#614 Add pulsar-client-reactive-api to spring-pulsar-reactive
  gradle/libs.versions.toml
  spring-pulsar-reactive/spring-pulsar-reactive.gradle
Labels: theme: build

#615 PORT "Add pulsar-client-reactive-api to spring-pulsar-reactive"
  gradle/libs.versions.toml
  spring-pulsar-reactive/spring-pulsar-reactive.gradle
Labels: theme: build

#622 Add Java 21 support for running tests
  .github/workflows/check-samples.yml
  build.gradle
  buildSrc/src/main/java/org/springframework/pulsar/gradle/JavaConventionsPlugin.java
  buildSrc/src/main/java/org/springframework/pulsar/gradle/RootProjectPlugin.java
  buildSrc/src/main/java/org/springframework/pulsar/gradle/toolchain/ToolchainExtension.java
  buildSrc/src/main/java/org/springframework/pulsar/gradle/toolchain/ToolchainPlugin.java
  gradle/java-conventions.gradle
Labels: theme: build

#625 [Release 1.1.0-M2] Update to next Boot snapshot
  gradle.properties
  gradle/libs.versions.toml
Labels: type: task

#624 [Release 1.0.4] Update to next Boot snapshot
  gradle.properties
  gradle/libs.versions.toml
Labels: type: task
